---
title: "Strings and Factors"
output: github_document
---

```{r eval = FALSE}
#一般画图的操作：预先设定好自己喜欢的theme和color
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal()+theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
library(rvest)
library(p8105.datasets)
library(tidyverse)
```

## Strings
```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec,"jeff")

str_replace(string_vec, "jeff", "Jeff")

str_replace(string_vec, "e", "E")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

#beginning of a line
str_detect(string_vec, "^i think")

#end of a line
str_detect(string_vec, "i think$")
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec, "pumpkin")

str_detect(string_vec, "Pumpkin")

str_detect(string_vec, "PUMPKIN")

## multiple choice(中括号内部表示出现a/b都可以)
str_detect(string_vec, "[Pp]umpkin")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "[0-9][a-zA-Z]")
```

a little weirder
```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

# .表示匹配一切
str_detect(string_vec, "7.11")
```

How things start to get real strange
```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

# Some characters are “special”. These include [ and ], ( and ), and .. If you want to search for these, you have to indicate they’re special using \. Unfortunately, \ is also special, so things get weird.
str_detect(string_vec, "\\[")
```

## Factors
```{r}
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex
as.numeric(vec_sex)
```

do some releveling
```{r}
#把male放在前面，转换成数字时male就变成了1
vec_sex = fct_relevel(vec_sex, "male")
vec_sex
as.numeric(vec_sex)
```

## Revisit some examples in the past
### NSDUH
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(nsduh_url)

marj_use_df = 
  drug_use_html |>
  html_table() |>
  first() |>
  slice(-1)
```

```{r}
data_marj = 
  marj_use_df |>
  select(-contains("P Value")) |>
  pivot_longer(
    cols = -State,
    names_to = "age_year",
    values_to = "percent"
  ) |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_remove(percent, "[a-c]$"),
    percent = as.numeric(percent)
  )
```

```{r}
data_marj |>
  filter(age == "12-17") |>
  ##把 state按照percent重新排序，才会获得从小到大的
  mutate(State = fct_reorder(State, percent)) |>
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

### One more example NYC restaurant Inspections
```{r}
data("rest_inspec")

rest_inspec |> 
  group_by(boro, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(names_from = grade, values_from = n)
```

```{r}
rest_inspec = rest_inspec |> 
  filter(str_detect(grade, "[A-Z]"),
         !(boro == "Missing"))

rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |>
  mutate(boro = str_replace(boro, "MANHATTAN", "THE CITY"),
    boro = fct_infreq(boro)) |>
  ggplot(aes(x = boro)) +
  geom_bar()
```

One last thing about factors
```{r}
rest_inspec |>
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |>
  mutate(boro = fct_infreq(boro)) |>
  lm(zipcode ~ boro, data = _)
```









